export const SAMPLE_TEXTS = [
    "the quick brown fox jumps over the lazy dog and the world keeps spinning without a care",
    "code is poetry written in a language that only machines and dreamers truly understand",
    "every keystroke is a small act of creation building something from nothing at all",
    "the universe is not only stranger than we imagine it is stranger than we can imagine",
    "simplicity is the ultimate sophistication and complexity is often just confusion in disguise",
    "a good book is a time machine that takes you anywhere you want to go for free",
    "the best time to plant a tree was twenty years ago and the second best time is now",
    "mountains are just hills that refused to stop growing no matter what anyone said",
    "coffee is just a gentle reminder that mornings can be survived with enough caffeine",
    "the internet is a library where someone moved all the books and hid the catalog",
    "music is what feelings sound like when words are too small to hold them anymore",
    "space is really big and mostly empty and somehow that is both terrifying and beautiful",
    "a bug in the code is just a feature that nobody asked for and everyone got anyway",
    "the ocean does not apologize for its depth and neither should you for yours",
    "sleeping is basically just saving your game before the next level starts each morning",
    "trees are nature's way of reminding us that slow and steady wins the long game",
    "every great story begins with someone deciding they were tired of waiting around",
    "the night sky is a reminder that there are more suns out there than grains of sand here",
    "bread is just a vehicle for butter and anyone who disagrees has never lived fully",
    "dogs have figured out something humans are still trying to learn about unconditional love",
    "a map is useless unless you know where you are standing when you look at it",
    "the keyboard is mightier than the sword especially when you know how to type fast",
    "rain is just the sky doing its laundry and forgetting to warn everyone below",
    "time zones exist to remind us that someone is always having breakfast while you sleep",
    "every expert in the world was once a beginner who refused to stay that way",
    "the fridge is just a cold box of potential meals waiting for inspiration to strike",
    "clouds are proof that even formless things can be beautiful without trying too hard",
    "procrastination is just excitement about something you have not started feeling yet",
    "a programmer's best tool is not the keyboard it is the ability to think clearly",
    "autumn is the season where the trees show us how beautiful letting go can look",
    "silence is a conversation too and sometimes it says more than any word ever could",
    "the moon has been watching humans make mistakes for billions of years without comment",
    "cats are small furry philosophers who have decided that napping is peak enlightenment",
    "every city has a heartbeat and if you walk long enough you will start to feel it",
    "the best code is code you never have to look at again because it just works",
    "dreams are your brain's way of making movies when you forgot to bring a book",
    "a pencil and a blank page are still the most powerful creative tools ever invented",
    "the wind has no shape but it moves everything it touches and remembers nothing",
    "sugar dissolves in water the way hard days dissolve into sleep when you finally rest",
    "technology is just magic that has been explained and magic is just tech we don't get yet",
    "the best journeys are the ones where you forget to check how much time has passed",
    "stars are just distant suns that look small because we are very far from home",
    "a library is proof that sharing ideas costs nothing and gains everything for everyone",
    "the fastest typist in the room is not always the smartest but it definitely looks cool",
    "rivers don't ask permission to find their way they just keep moving through everything",
    "pizza was invented because someone decided bread was too boring to eat by itself",
    "fog is just a cloud that decided to take a walk at ground level for a change",
    "every line of code you write is a tiny decision that might matter years from now",
    "the alphabet is just twenty six shapes that humans agreed could mean the whole world",
    "a good night's sleep is underrated by everyone who has not missed one yet",
    "the sun sets in every country at the end of every day and somehow that is comforting",
    "language is the closest thing to telepathy that humans have managed to figure out",
    "bees have been doing their jobs longer than any company in the history of earth",
    "a sandwich is just a portable meal that someone was too hungry to wait to plate",
    "curiosity is the engine that runs every discovery humans have ever stumbled into",
    "the desert looks empty until you learn to see everything that lives within it quietly",
    "every password you create is a tiny secret between you and the machine you trust",
    "the best teams are made of people who trust each other more than they trust the plan",
    "sunrise is the earth's daily promise that darkness is always temporary no matter what",
    "a keyboard shortcut is a love letter from a developer to everyone who hates using mice",
    "the sky changes color every morning to remind you that yesterday is completely gone",
    "habits are just decisions that got tired of being made and decided to run automatically",
    "a forest is millions of lives all living together without a meeting or a manager",
    "great ideas often arrive in the shower because the brain finally gets a moment of peace",
    "the human brain can recognize a face in milliseconds but forgets where keys are always",
    "every mountain peak looks impossible from the base and obvious from the summit",
    "reading is the closest thing to downloading someone else's thoughts directly into yours",
    "the letter q almost always needs u and that is the most loyal relationship in language",
    "sunflowers turn to face the sun every day which is a good reminder for everyone",
    "the fastest code is the code that runs once and never needs to be touched again",
    "autumn leaves fall because trees know how to let go of what is no longer needed",
    "a city at night looks like a circuit board that someone forgot to turn off at dusk",
    "the best way to predict the future is to build it one small decision at a time",
    "lightning is just the sky reminding you that electricity existed long before outlets did",
    "a deadline is a creative force disguised as a threat and both things are equally true",
    "the world is full of people who almost started something and called it being realistic",
    "every sandwich is a tiny engineering problem solved with bread and good intentions",
    "the keyboard layout was designed long ago and nobody has had the courage to change it",
    "snowflakes are the sky's way of decorating the ground when it gets tired of being gray",
    "a codebase is like a city built by many hands with very different ideas about roads",
    "the fastest runner in the room still has to start before they can finish anything",
    "fog in the morning makes the world feel like it belongs to whoever woke up first",
    "a variable name is a promise you make to the next person who reads your code",
    "the ocean has seen every ship and swallowed enough secrets to fill ten thousand books",
    "great writing is just clear thinking that someone was patient enough to put into words",
    "the best part of any trip is the version of yourself you bring back at the end",
    "clouds move without engines across the entire sky and ask nothing in return ever",
    "a to do list is just a wish list with deadlines attached to make it feel official",
    "the earth rotates at a thousand miles per hour and you have never once felt it move",
    "every app you use was once just an idea someone refused to stop thinking about",
    "the color blue looks different to everyone and yet we all agree to call it the same",
    "winter mornings have a quiet that no other season manages to pull off quite as well",
    "a function should do one thing well and not apologize for having such a clear purpose",
    "the best conversations happen when nobody is trying to win and everyone is just curious",
    "gravity is the universe's way of making sure nothing drifts too far from everything else",
    "a warm cup of tea is proof that small things can make a difficult day more manageable",
    "the first step in any project is always the hardest because it requires believing it's possible",
    "debugging is just detective work for people who would rather talk to computers than people",
    "the sun does not rise or set it just stays there while we spin past it twice a day",
];